
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="alert alert-danger">
            <strong>Aviso!</strong>
            Você não tem permissão de acessar esta página.<br><br>
            <button type="button" onclick="history.back(-1);" class="btn btn-danger">
                <i class="fa fa-chevron-left"></i>
                Voltar
            </button>
        </div>
    </div>
</div>