<?php
    $this->headScript()->appendFile($this->basePath() . '/js/application/cliente/index.js');
?>

<ol class="breadcrumb">
    <li><a href="<?php echo $this->url('home') ?>">Início</a></li>
    <li class="active">Usuário</li>
</ol>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <h3>Usuário</h3>
    </div>
    <div class="col-sm-6 col-md-6">
        <div class="btn-group pull-right">
        	<?php if($this->acoes['criar']):?>
            <a href="<?php echo $this->url('usuario', array('action' => 'criar')) ?>" class="btn btn-primary btn-lg">
                <i class="fa fa-plus"></i>
                <i class="fa fa-user"></i>
				Usuário
            </a>
            <?php endif;?>
        </div>
    </div>
</div>

<hr/>

<div class="row">
    <div class="col-sm-6 col-md-6">
        <form method="get" role="form">
            <div class="row">
                <div class="col-sm-8 col-md-6">
                    <input type="text" name="restricao" autofocus="autofocus" value="<?php echo $this->restricao ?>"
                           class="form-control" placeholder="Buscar Login...">
                </div>
                <div class="col-sm-3 col-md-3">
                    <button type="submit" class="btn btn-primary">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <?php
            $count = count($list);
            echo $this->partial('partials/paginacao/paginacao', array(
                'pagina' => (int) $this->pagina,
                'route' => 'usuario',
                'count' => $count,
                'restricao' => $this->restricao
            ));
        ?>
    </div>
</div>

<hr>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <table class="table table-hover table-striped">
            <thead>
                <tr>
                    <th>CÓD.</th>
                    <th>Login</th>
                    <th style="width: 120px;">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($list as $item): ?>
                <tr>
                    <td><?php echo $item->id ?></td>
                    <td><?php echo $item->login ?></td>
                    <td style="text-align: right;" >
                        <div class="btn-group">
                            <?php if($acoes['editar']):?>
                            <a href="<?php echo $this->url('usuario',
                                    array('action' => 'editar', 'id' => $item->id)); ?>"
                               class="btn btn-default" rel="tooltip" title="Editar">
                                <i class="fa fa-edit"></i>
                            </a>
                            <?php endif;?>

                            <?php if($acoes['deletar']):?>
                            <a href="<?php echo $this->url('usuario',
                                    array('action' => 'deletar', 'id' => $item->id)); ?>"
                               class="btn btn-danger deletar" rel="tooltip" title="Deletar">
                                <i class="fa fa-times"></i>
                            </a>
                            <?php endif;?>
                        </div>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="row">
    <div class="col-md-6 col-md-offset-6">
        <?php
            echo $this->partial('partials/paginacao/paginacao', array(
                'pagina' => (int) $this->pagina,
                'route' => 'usuario',
                'count' => $count,
                'restricao' => $this->restricao
            ));
        ?>
    </div>
</div>
